### PR TITLE
Priming tower extrusion amount

### PR DESCRIPTION
**Pull request by Nibbels**
I already opened an issue https://github.com/mkudzia84/toolchanger-pspp/issues/3
Now I did test the changed code on my printer and the amount of material I see is much better than before. Do you confirm that the extrusion is a bit odd on your original version?

The only commit which is interesting is https://github.com/mkudzia84/toolchanger-pspp/pull/4/commits/fe2158420d5a8b20665ac0133ed9a846359c0abd

Feel free review the changes.
If you like I can rework the PR afterwards - or you just copy the parts you (maybe) want and commit them by yourself.

### CODE REVIEW

**Comment by mkudzia84** [comment]
Hello, Will have a look at this, for sure looking at it - extrusion formula looks a bit too funky for what it should be.
I will check the code and your pull request and try to remember what was the rationale behind it

**Comment by mkudzia84** [comment]
Ok - I definetly made a mistake in the formula (probably late night coding)

So in my opinion Extrusion Length should be calculated in the following way:
With:
- Nozzle Diameter Nd
- Filament Diameter Fd
- Distance of the travel d
- Layer height h

Considering we are moving round object from point P1 to P2 on distance d
Volume of material extruder is
V = (Nd * d + PI * (Nd)^2)  * h - this may yield slight overextrusion at the begining and end of the move 
Other option would be
V = Nd * d * h

The lengthj of the material that needs to be extruded:
E = [V / (PI * (Fd / 2) ^ 2] * extrusion_multiplier 
Which is
E = [4 * V / (Pi * FD^2)] * extrusion_multiplier

**Comment by mkudzia84** [comment]
I think you can skip that fact thing you added that is equal to 1.2
Because you just compensated for the lack of the Pi * (Nd)^2 segment - which for 0.4 nozzle is ~0.12
V = (Nd * d + PI * (Nd)^2) * h

**Comment by Nibbels** [comment]
The factor 1.2 is supposed to make the drawn line a bit thicker than the nozzle size is. So the material is a bit more pushed down to the build plate because it has to expand to the sides. Of course we can print at nozzle diameter or even a bit less, but if we want more build plate adhesion some people might want to adjust the first layers width a tiny bit.

(I did compensate the added 20% material flow by making the lines 20% more wide. So the amount of material per volume is still 100%.)

:)

**Comment by Nibbels** [comment]
I close this PR, because it is not necessary anymore.

**Pull request closed without merging**
